### PR TITLE
Add some of the PlantSeg models

### PR DESCRIPTION
**Pull request by wolny**

### CODE REVIEW

**Comment by wolny** [comment]
dunno why Travis complains, YAML files (both the model list and model descriptors) are correct

**Comment by FynnBe** [comment]
the manifest points to outdated models, such as: 
invalid model: https://raw.githubusercontent.com/bioimage-io/pytorch-bioimage-io/v0.1.1/specs/models/unet2d/nuclei_broad/UNet2DNucleiBroad.model.yaml

I'll fix this soon

**Comment by k-dominik** [comment]
blocked, probably resolvable with #12

**Comment by FynnBe** [comment]
tests run, but I am puzzled by the output for some of the models, e.g.
```
invalid model: https://github.com/hci-unihd/plant-seg/blob/ff9ebdb890dc57efee3d33933cd5b3a6862fe9ab/bioimage-io/UNet2DArabidopsisOvules.model/UNet2DArabidopsisOvules.model.yaml
ScannerError(None, None, 'mapping values are not allowed in this context', <_ruamel_yaml.Mark object at 0x7fa632552c70>)
```
Locally UNet2DArabidopsisOvules.model.yaml almost passed (minor fix https://github.com/hci-unihd/plant-seg/pull/87)
No idea how the ScannerError was produced...

**Comment by k-dominik** [comment]
any update on this..?

**Comment by wolny** [comment]
@k-dominik @FynnBe I've updated the schema to v0.3.2 and all of my specs are passing now, but other specs are still failing. I think we can merge this and fix the non-plantseg specs in a separate PR

**Pull request merged**
