### PR TITLE
update validation command

### PR DESCRIPTION
**Pull request by FynnBe**

### CODE REVIEW

**Comment by constantinpape** [comment]
Not sure if this is working at all, see https://github.com/bioimage-io/spec-bioimage-io/issues/324.

**Comment by constantinpape** [comment]
@FynnBe any chance we can fix the test here so that I can merge #40?

**Comment by FynnBe** [comment]
now fails only due to missing https://github.com/bioimage-io/spec-bioimage-io/pull/336 in current release. Should work with next release...

**Comment by constantinpape** [comment]
It passes now, thanks @FynnBe

**Pull request merged**
